# Generated by Django 4.1.3 on 2022-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0008_barcodepun_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodepun',
            name='extended_part_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
