# Generated by Django 4.1.5 on 2023-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0014_delete_lasermarkqualityscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasermarkduplicatescan',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
