# Generated by Django 4.1.5 on 2023-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0015_alter_lasermarkduplicatescan_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermark',
            name='grade',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
