# Generated by Django 4.1.5 on 2023-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0016_lasermark_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermark',
            name='asset',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
