# Generated by Django 4.1.5 on 2023-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0018_alter_lasermark_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodepun',
            name='parts_per_layer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
