# Generated by Django 4.2.13 on 2024-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0020_remove_barcodepun_parts_per_layer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateBarcodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=50)),
                ('scan_time', models.DateTimeField()),
                ('unlock_code', models.CharField(max_length=3)),
                ('employee_id', models.CharField(max_length=10, null=True)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
    ]
