# Generated by Django 4.2.13 on 2024-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0021_duplicatebarcodeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicatebarcodeevent',
            name='event_time',
            field=models.DateTimeField(),
        ),
    ]
