# Generated by Django 4.2.13 on 2024-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0022_alter_duplicatebarcodeevent_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatebarcodeevent',
            name='user_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
