# Generated by Django 4.2.13 on 2024-09-26 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0023_duplicatebarcodeevent_user_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unlock_code', models.CharField(max_length=10)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
    ]
