# Generated by Django 4.2.13 on 2024-09-25 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0023_duplicatebarcodeevent_user_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchLockoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodes', models.TextField()),
                ('part_number', models.CharField(max_length=255)),
                ('unlock_code', models.CharField(max_length=3)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unlocked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
