# Generated by Django 4.2.13 on 2024-08-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0023_duplicatebarcodeevent_user_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateBatchUtilityScan',
            fields=[
                ('laser_mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barcode.lasermark')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
    ]
