# Generated by Django 4.2.13 on 2024-08-30 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0023_duplicatebarcodeevent_user_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateBatchUtilityScan',
            fields=[
                ('laser_mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barcode.lasermark')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('part_number_utility', models.CharField(default='', max_length=20)),
                ('bar_code_utility', models.CharField(default='TEMPORARY_UNIQUE_VALUE', max_length=50, unique=True)),
                ('created_at_utility', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_utility', models.CharField(default='N', max_length=1, null=True)),
                ('asset_utility', models.CharField(default='', max_length=8, null=True)),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
    ]
