# Generated by Django 4.2.13 on 2024-10-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0024_lockoutevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasermark',
            name='unique_portion',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
