# Generated by Django 4.2.13 on 2024-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0024_duplicatebatchutilityscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatebatchutilityscan',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
