# Generated by Django 4.2.13 on 2024-09-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0025_duplicatebatchutilityscan_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duplicatebatchutilityscan',
            name='asset_utility',
        ),
    ]
