# Generated by Django 4.2.13 on 2024-09-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0026_remove_duplicatebatchutilityscan_asset_utility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicatebatchutilityscan',
            options={'ordering': ['created_at_utility']},
        ),
        migrations.RemoveField(
            model_name='duplicatebatchutilityscan',
            name='scanned_at',
        ),
    ]
