# Generated by Django 4.2.13 on 2024-09-04 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0027_alter_duplicatebatchutilityscan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatebatchutilityscan',
            name='scanned_at_utility',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
