# Generated by Django 4.1.5 on 2023-02-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_variables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariableModel',
            new_name='SiteVariableModel',
        ),
    ]
