# Generated by Django 4.2.2 on 2023-08-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part_for_machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partformachineevent',
            old_name='date',
            new_name='datetime',
        ),
    ]
