# Generated by Django 4.2.13 on 2024-08-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('operator', models.CharField(blank=True, max_length=256, null=True)),
                ('shift', models.IntegerField(blank=True, null=True)),
                ('qtyInspected', models.IntegerField(blank=True, null=True)),
                ('totalDefects', models.IntegerField(blank=True, null=True)),
                ('totalAccepted', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('detailOther', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feat',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FeatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featName', models.CharField(max_length=256)),
                ('defects', models.IntegerField()),
                ('scrap_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feat_entries', to='quality.scrapform')),
            ],
        ),
    ]
