# Generated by Django 4.2.13 on 2024-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_feat_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.CharField(max_length=256)),
                ('part_number', models.CharField(max_length=256)),
                ('feat_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
