# Generated by Django 4.2.13 on 2024-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_supervisorauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapform',
            name='tpc_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
