# Generated by Django 4.2.13 on 2024-08-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_feat_critical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapform',
            old_name='qtyInspected',
            new_name='qtyPacked',
        ),
    ]
