# Generated by Django 4.2.13 on 2024-08-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_rename_qtyinspected_scrapform_qtypacked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapform',
            old_name='totalAccepted',
            new_name='totalInspected',
        ),
    ]
