# Generated by Django 4.2.13 on 2024-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
        ('quality', '0009_rename_totalaccepted_scrapform_totalinspected'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityPDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('associated_parts', models.ManyToManyField(related_name='pdf_documents', to='plant.part')),
            ],
        ),
    ]
