# Generated by Django 4.2.13 on 2024-09-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_qualitypdfdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_number', models.CharField(max_length=20)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_records', to='quality.qualitypdfdocument')),
            ],
        ),
    ]
