# Generated by Django 4.2.13 on 2024-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_viewingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitypdfdocument',
            name='category',
            field=models.CharField(choices=[('QA', 'Quality Alerts'), ('SI', 'Special Instruction'), ('TPC', 'TPC'), ('VAC', 'Visual Acceptance Criteria'), ('PMR', 'Part Marking Requirement')], default='QA', max_length=10),
        ),
    ]
