# Generated by Django 4.2.15 on 2024-11-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
        ('quality', '0012_qualitypdfdocument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_message', to='plant.part')),
            ],
        ),
    ]
