# Generated by Django 4.2.15 on 2024-11-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
        ('quality', '0014_partmessage_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedRabbitsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_number', models.CharField(max_length=20)),
                ('shift', models.PositiveSmallIntegerField()),
                ('verification_okay', models.BooleanField()),
                ('supervisor_comments', models.TextField(blank=True, null=True)),
                ('supervisor_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_rabbits_entries', to='plant.part')),
            ],
        ),
    ]
