# Generated by Django 4.2.15 on 2024-11-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
        ('quality', '0016_redrabbittype_redrabbitsentry_red_rabbit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='redrabbittype',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red_rabbit_types', to='plant.part'),
        ),
    ]
