# Generated by Django 4.2.18 on 2025-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0018_qualitytagdropdownoptions_and_more'),
    ]