# Generated by Django 4.2.18 on 2025-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0019_qualitytag_alter_qualitypdfdocument_category'),
    ]