# Generated by Django 4.2.18 on 2025-02-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
        ('quality', '0021_qualitytag_alter_qualitypdfdocument_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitypdfdocument',
            name='category',
            field=models.CharField(choices=[('QA', 'Quality Alerts'), ('SI', 'Special Instruction'), ('TPC', 'TPC'), ('VAC', 'Visual Acceptance Criteria'), ('PMR', 'Part Marking Requirement'), ('CT', 'Certification Tag')], default='QA', max_length=10),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='plant.part')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='plant.part')),
            ],
        ),
    ]
