# Generated by Django 4.2.18 on 2025-02-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0023_qualitytag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='part',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='part',
        ),
        migrations.DeleteModel(
            name='QualityTag',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
