# Generated by Django 4.2.18 on 2025-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_rename_part_tally_part'),
        ('quality', '0024_remove_customer_part_remove_operation_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255, unique=True)),
                ('part_number', models.JSONField()),
                ('assets', models.ManyToManyField(related_name='parts', to='plant.asset')),
                ('customers', models.ManyToManyField(related_name='parts', to='quality.customer')),
                ('operations', models.ManyToManyField(related_name='parts', to='quality.operations')),
            ],
        ),
    ]
