# Generated by Django 4.2.18 on 2025-02-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0025_customer_operations_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='part',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='part',
            name='operations',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
