# Generated by Django 4.2.13 on 2024-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_formquestionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestionanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='formquestionanswer',
            name='answer_type',
            field=models.CharField(choices=[('textarea', 'Textarea'), ('number', 'Number Input'), ('dropdown', 'Dropdown'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox'), ('time', 'Time Input')], default='textarea', max_length=50),
        ),
        migrations.AddField(
            model_name='formquestionanswer',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
