# Generated by Django 4.2.13 on 2024-10-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formanswer_formquestion_delete_formquestionanswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='answer',
            field=models.JSONField(),
        ),
    ]
