# Generated by Django 4.2.13 on 2024-10-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_formanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
