# Generated by Django 4.2.15 on 2024-11-07 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_form_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswer',
            name='operator_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
