# Generated by Django 4.2.18 on 2025-02-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_form_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formanswer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
