# Generated by Django 4.2.5 on 2023-09-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_Production_Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=20)),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('goal', models.IntegerField()),
            ],
        ),
    ]
