# Generated by Django 4.1.5 on 2023-10-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekly_Production_Goals',
            new_name='Weekly_Production_Goal',
        ),
        migrations.AlterModelOptions(
            name='weekly_production_goal',
            options={'ordering': ['-year', '-week']},
        ),
    ]
