# Generated by Django 4.2.15 on 2024-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0002_rename_weekly_production_goals_weekly_production_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAMachineTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50)),
                ('effective_date_unix', models.BigIntegerField()),
                ('target', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
