# Generated by Django 4.2.15 on 2024-12-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_query', '0003_oamachinetargets'),
    ]

    operations = [
        migrations.AddField(
            model_name='oamachinetargets',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
