# Generated by Django 4.2.13 on 2024-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_alter_password_machine_delete_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedpassword',
            name='label',
            field=models.CharField(default='No Label', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password',
            name='label',
            field=models.CharField(default='No Label', max_length=100),
            preserve_default=False,
        ),
    ]
