# Generated by Django 4.1.2 on 2022-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=7)),
                ('bar_code', models.CharField(max_length=50, unique=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
