# Generated by Django 4.1.2 on 2022-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_verify', '0002_barcodepun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodepun',
            name='part',
            field=models.CharField(max_length=50),
        ),
    ]
