# Generated by Django 4.1.2 on 2022-10-21 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_verify', '0004_alter_barcodepun_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMarkMeasurementData',
            fields=[
                ('laser_mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barcode_verify.lasermark')),
                ('measurement_data', models.TextField()),
            ],
            options={
                'ordering': ['laser_mark'],
            },
        ),
        migrations.AlterModelOptions(
            name='lasermark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lasermark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lasermark',
            name='scanned_at',
            field=models.DateTimeField(),
        ),
    ]
