# Generated by Django 4.2.13 on 2024-08-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='machine',
        ),
        migrations.AddField(
            model_name='password',
            name='password_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plant.asset'),
        ),
    ]
