# Generated by Django 4.2.13 on 2024-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_remove_password_machine_password_password_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
