# Generated by Django 4.2.18 on 2025-03-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCycleTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.IntegerField()),
                ('effective_date', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.asset')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.part')),
            ],
        ),
    ]
