# Generated by Django 4.2.15 on 2024-12-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPM_Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('question_group', models.CharField(choices=[('TPM', 'TPM'), ('Safety Check', 'Safety Check'), ('Process Machine Checks', 'Process Machine Checks'), ('5S Checks', '5S Checks')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionaires', to='plant.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questionaires', models.ManyToManyField(related_name='questions', to='plant.tpm_questionaire')),
            ],
        ),
    ]
