# Generated by Django 4.2.18 on 2025-03-10 14:35

from django.db import migrations, models
import plant.models.setupfor_models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_asset_asset_name_part_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupfor',
            name='created_at',
            field=models.BigIntegerField(default=plant.models.setupfor_models.current_epoch, editable=False),
        ),
        migrations.AlterField(
            model_name='setupfor',
            name='since',
            field=models.BigIntegerField(),
        ),
    ]
