# Generated by Django 4.2.18 on 2025-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_assetcycletimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcycletimes',
            name='cycle_time',
            field=models.FloatField(),
        ),
    ]
