# Generated by Django 4.2.15 on 2024-12-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_tpm_questionaire_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tpm_questionaire',
            old_name='created_at',
            new_name='effective_date',
        ),
    ]
