# Generated by Django 4.2.15 on 2024-11-11 19:20

from django.db import migrations, models
import plant.models.setupfor_models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_setupfor_created_at_alter_setupfor_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupfor',
            name='created_at',
            field=models.BigIntegerField(default=plant.models.setupfor_models.get_unix_timestamp),
        ),
    ]
