# Generated by Django 4.2.15 on 2024-12-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_rename_created_at_tpm_questionaire_effective_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpm_questionaire',
            name='question_group',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_group',
            field=models.CharField(choices=[('TPM', 'TPM'), ('Safety Check', 'Safety Check'), ('Process Machine Checks', 'Process Machine Checks'), ('5S Checks', '5S Checks')], default='TPM', max_length=50),
            preserve_default=False,
        ),
    ]
