# Generated by Django 4.2.15 on 2024-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_remove_tpm_questionaire_question_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
