# Generated by Django 4.2.15 on 2024-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_questions_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('YN', 'Yes/No'), ('NUM', 'Numeric Input')], default='YN', max_length=10),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_group',
            field=models.CharField(choices=[('TPM', 'TPM'), ('Safety Check', 'Safety Check'), ('Process Machine Checks', 'Process Machine Checks'), ('6S Checks', '6S Checks')], max_length=50),
        ),
    ]
