# Generated by Django 4.2.15 on 2024-12-13 19:46

from django.db import migrations, models
import django.db.models.deletion
import plant.models.tpm_models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_questions_type_alter_questions_question_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_group',
            field=models.CharField(choices=[('TPM', 'TPM'), ('Process Machine Checks', 'Process Machine Checks'), ('6S Checks', '6S Checks')], max_length=50),
        ),
        migrations.CreateModel(
            name='TPM_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_number', models.PositiveIntegerField()),
                ('shift', models.PositiveIntegerField(choices=[(1, 'Shift 1'), (2, 'Shift 2'), (3, 'Shift 3')])),
                ('date', models.DateField()),
                ('answers', models.JSONField()),
                ('submitted_at', models.BigIntegerField(default=plant.models.tpm_models.get_current_epoch)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='plant.asset')),
            ],
        ),
    ]
