# Generated by Django 4.2.15 on 2024-12-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_alter_questions_question_group_tpm_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='questionaires',
        ),
        migrations.CreateModel(
            name='QuestionaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionaire_questions', to='plant.questions')),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionaire_questions', to='plant.tpm_questionaire')),
            ],
        ),
    ]
