# Generated by Django 4.2.15 on 2024-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_remove_questions_questionaires_questionairequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionairequestion',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionairequestion',
            name='order',
            field=models.FloatField(default=0.0),
        ),
    ]
