# Generated by Django 4.2.13 on 2024-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLifeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(choices=[('788', '788'), ('789', '789'), ('790', '790'), ('791', '791'), ('792', '792'), ('793', '793'), ('794', '794')], max_length=128)),
                ('operation', models.CharField(choices=[('10', 'OP-10'), ('20', 'OP-20'), ('30', 'OP-30')], max_length=128)),
                ('shift', models.CharField(choices=[('Mornings', 'Mornings'), ('Afternoons', 'Afternoons'), ('Midnights', 'Midnights'), ('Continental-A', 'Continental-A'), ('Continental-B', 'Continental-B')], max_length=128)),
                ('operator', models.CharField(max_length=128)),
                ('tool_type', models.CharField(choices=[('Drill', 'Drill'), ('Reamer', 'Reamer')], max_length=128)),
                ('tool_status', models.CharField(max_length=128)),
                ('tool_issue', models.CharField(choices=[('Machine Issue', 'Machine Issue'), ('Oversize Holes', 'Oversize Holes'), ('Undersize Holes', 'Undersize Holes'), ('Hole Positions', 'Hole Positions are out'), ('Burnt Holes', 'Burnt Holes'), ('Insufficient Coolant', 'Insufficient Coolant'), ('Dropped', 'Tool Dropped'), ('Wrong Offset', 'Wrong Offset'), ('Incorrect Part Load', 'Incorrect Part Load'), ('Tooling Issue', 'Wrong Setup by Toolroom'), ('Other', 'Other')], max_length=128)),
                ('expected_tool_life', models.IntegerField()),
                ('actual_tool_life', models.IntegerField()),
                ('tool_serial_number', models.CharField(max_length=128)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
