# Generated by Django 4.1.3 on 2022-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0007_rename_scanned_at_lasermark_duplicate_scan_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodepun',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
