# Generated by Django 4.1.3 on 2023-01-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0010_remove_barcodepun_extended_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserMarkDuplicateScan',
            fields=[
                ('laser_mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barcode.lasermark')),
                ('scanned_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='LaserMarkQualityScan',
            fields=[
                ('laser_mark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='barcode.lasermark')),
                ('scanned_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
    ]
