# Generated by Django 4.1.3 on 2023-01-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0013_lasermarkqualityscan_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaserMarkQualityScan',
        ),
    ]
