# Generated by Django 4.2.2 on 2023-06-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
